### ISSUE TITLE
GET /fileasnetcdf seems not to work

### ISSUE THREAD

**Issue by rbardaji** [EMSODEV/emsodev-api#2]
A GET from the following endpoint:                

http://api.emsodev.eu/fileasnetcdf?observatory=EMSODEV-EGIM-node00001&instrument=37-14998&parameter=sea_water_temperature&startDate=01%2F01%2F2017                                               It 

does not return the netCDF

**Comment by UmbertoApponi** [comment]
With the following: 
http://api.emsodev.eu/fileasnetcdf?observatory=EMSODEV-EGIM-node00001&instrument=37-14998&parameter=sea_water_temperature&startDate=17%2F03%2F2017&endDate=23%2F03%2F2017

In which you have to insert/modify endDate and startDate values. The retrived file is in NetCDF format.
