### ISSUE TITLE
Internal Server Error in instruments endpoint

### ISSUE THREAD

**Issue by rbardaji** [EMSODEV/emsodev-api#5]
A GET from the following endpoint:

http://api.emsodev.eu/observatories/EMSODEV-EGIM-node00001/instruments

returns the following output JSON:

{
  "timestamp": 1534158146554,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.web.client.HttpClientErrorException",
  "message": "403 Forbidden",
  "path": "/observatories/EMSODEV-EGIM-node00001/instruments"
}

Could you check it?

Thanks

**Comment by leandrolombardo** [comment]
The Instruments API is again up and runnig. 
There was a problem into the Big Data Platform that now has been solved.
Regards
